apiVersion: v1
kind: ServiceAccount
metadata:
  name: bastion-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crownlabs-bastion-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crownlabs-bastion-operator
subjects:
  - kind: ServiceAccount
    name: bastion-operator
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-bastion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ssh-bastion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2020-09-12T12:59:32Z"
      creationTimestamp: null
      labels:
        app: ssh-bastion
    spec:
      serviceAccountName: bastion-operator
      containers:
      - name: bastion
        args: ["-D", "-e", "-f","/etc/ssh/sshd_config_custom"]
        command: ["/usr/sbin/sshd"]
        image: claudious96/ssh-bastion:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/bastion/.ssh
          name: authorized-keys
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: authorized-keys
          configMap:
            name: auth-keys-bastion
            defaultMode: 0444

---
apiVersion: v1
data:
  authorized_keys: |
    # Just a comment to fill in the configmap and start the pod
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: auth-keys-bastion

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-bastion
spec:
  ports:
    - port: 2222
      targetPort: 2222
      name: ssh
  selector:
    app: ssh-bastion
  type: LoadBalancer
