apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-bastion-operator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list","watch"]

- apiGroups: [""]
  resources: ["secrets","services","events"]
  verbs: ["get","list","watch","create"]

- apiGroups: ["crownlabs.polito.it"]
  resources: ["tenants"]
  verbs: ["list","watch"]
